from collections import namedtuple, defaultdict

from data import Color, Graphic, MobID, MobTag, Point
from items import ItemID


# First item is the result, the rest are the ingredients.
recipies = {
    MobID.WORKBENCH: (
        ((ItemID.WORKBENCH, 1), (ItemID.WOOD, 10)),
        ((ItemID.OVEN, 1), (ItemID.STONE, 10)),
        ((ItemID.FURNACE, 1), (ItemID.STONE, 20)),
        ((ItemID.ANVIL, 1), (ItemID.IRON_BAR, 5)),
        ((ItemID.LOOM, 1), (ItemID.WOOD, 10), (ItemID.STRING, 5)),
        ((ItemID.BOOKCASE, 1), (ItemID.WOOD, 10), (ItemID.BOOK, 5)),
        ((ItemID.TORCH, 2), (ItemID.WOOD, 2), (ItemID.COAL, 1)),
        ((ItemID.WOOD_LANTERN, 1), (ItemID.WOOD, 5), (ItemID.SLIME, 4), (ItemID.CLOTH, 2), (ItemID.GLASS, 4)),
        ((ItemID.WOOD_SWORD, 1), (ItemID.WOOD, 5)),
        ((ItemID.WOOD_PICK, 1), (ItemID.WOOD, 5)),
        ((ItemID.WOOD_AXE, 1), (ItemID.WOOD, 5)),
        ((ItemID.WOOD_SHOVEL, 1), (ItemID.WOOD, 5)),
        ((ItemID.WOOD_HOE, 1), (ItemID.WOOD, 5)),
        ((ItemID.FISH_SPEAR, 1), (ItemID.WOOD, 5), (ItemID.STRING, 5)),
        ((ItemID.STONE_SWORD, 1), (ItemID.WOOD, 5), (ItemID.STONE, 5)),
        ((ItemID.STONE_PICK, 1), (ItemID.WOOD, 5), (ItemID.STONE, 5)),
        ((ItemID.STONE_AXE, 1), (ItemID.WOOD, 5), (ItemID.STONE, 5)),
        ((ItemID.STONE_SHOVEL, 1), (ItemID.WOOD, 5), (ItemID.STONE, 5)),
        ((ItemID.STONE_HOE, 1), (ItemID.WOOD, 5), (ItemID.STONE, 5)),
        ((ItemID.WOOD_FLOOR, 1), (ItemID.WOOD, 4)),
        ((ItemID.WOOD_WALL, 1), (ItemID.WOOD, 8)),
        ((ItemID.WOOD_DOOR, 1), (ItemID.WOOD, 8)),
        ((ItemID.STONE_FLOOR, 1), (ItemID.STONE, 4)),
        ((ItemID.STONE_WALL, 1), (ItemID.STONE, 8)),
    ),
    MobID.OVEN: (
        ((ItemID.BREAD, 1), (ItemID.WHEAT, 5), (ItemID.WOOD, 2)),
        ((ItemID.COOKED_TUBER, 1), (ItemID.TUBER, 1), (ItemID.WOOD, 2)),
        ((ItemID.APPLE_PIE, 1), (ItemID.WHEAT, 5), (ItemID.APPLE, 5), (ItemID.WOOD, 2)),
        ((ItemID.PASTRY, 1), (ItemID.COOKED_TUBER, 5), (ItemID.WHEAT, 5), (ItemID.WOOD, 2)),
        ((ItemID.COOKED_FISH, 1), (ItemID.FISH, 1), (ItemID.WOOD, 2)),
        ((ItemID.COOKED_DEEP_FISH, 1), (ItemID.DEEP_FISH, 1), (ItemID.WOOD, 2)),
        ((ItemID.COOKED_DUCK_MEAT, 1), (ItemID.DUCK_MEAT, 1), (ItemID.WOOD, 2)),
        ((ItemID.BOILED_EGG, 1), (ItemID.DUCK_EGG, 1), (ItemID.WOOD, 2)),
    ),
    MobID.FURNACE: (
        ((ItemID.IRON_BAR, 1), (ItemID.IRON_ORE, 4), (ItemID.COAL, 1)),
        ((ItemID.GOLD_BAR, 1), (ItemID.GOLD_ORE, 4), (ItemID.COAL, 1)),
        ((ItemID.GLASS, 1), (ItemID.SAND, 4), (ItemID.COAL, 1)),
        ((ItemID.BOTTLE, 1), (ItemID.GLASS, 2), (ItemID.COAL, 1)),
        ((ItemID.WINDOW, 1), (ItemID.GLASS, 4),),
        ((ItemID.SKY_WINDOW, 1), (ItemID.GLASS, 4), (ItemID.CLOUD, 2),),
    ),
    MobID.ANVIL: (
        ((ItemID.IRON_LANTERN, 1), (ItemID.IRON_BAR, 5), (ItemID.SLIME, 4), (ItemID.CLOTH, 2), (ItemID.GLASS, 4)),
        ((ItemID.GOLD_TORCH, 1), (ItemID.TORCH, 4), (ItemID.GOLD_BAR, 2)),
        ((ItemID.GOLD_LANTERN, 1), (ItemID.GOLD_BAR, 5), (ItemID.SLIME, 4), (ItemID.CLOTH, 2), (ItemID.GLASS, 4)),
        ((ItemID.GEM_LANTERN, 1), (ItemID.GEM, 25), (ItemID.SLIME, 4), (ItemID.CLOTH, 2), (ItemID.GLASS, 4)),
        ((ItemID.CAULDRON, 1), (ItemID.IRON_BAR, 5),),
        ((ItemID.BUCKET, 1), (ItemID.IRON_BAR, 5), ),
        ((ItemID.IRON_SWORD, 1), (ItemID.WOOD, 5), (ItemID.IRON_BAR, 5)),
        ((ItemID.IRON_PICK, 1), (ItemID.WOOD, 5), (ItemID.IRON_BAR, 5)),
        ((ItemID.IRON_AXE, 1), (ItemID.WOOD, 5), (ItemID.IRON_BAR, 5)),
        ((ItemID.IRON_SHOVEL, 1), (ItemID.WOOD, 5), (ItemID.IRON_BAR, 5)),
        ((ItemID.IRON_HOE, 1), (ItemID.WOOD, 5), (ItemID.IRON_BAR, 5)),
        ((ItemID.IRON_FISH_SPEAR, 1), (ItemID.IRON_BAR, 5), (ItemID.STRING, 5)),
        ((ItemID.GOLD_SWORD, 1), (ItemID.WOOD, 5), (ItemID.GOLD_BAR, 5)),
        ((ItemID.GOLD_PICK, 1), (ItemID.WOOD, 5), (ItemID.GOLD_BAR, 5)),
        ((ItemID.GOLD_AXE, 1), (ItemID.WOOD, 5), (ItemID.GOLD_BAR, 5)),
        ((ItemID.GOLD_SHOVEL, 1), (ItemID.WOOD, 5), (ItemID.GOLD_BAR, 5)),
        ((ItemID.GOLD_HOE, 1), (ItemID.WOOD, 5), (ItemID.GOLD_BAR, 5)),
        ((ItemID.GOLD_FISH_SPEAR, 1), (ItemID.GOLD_BAR, 5), (ItemID.STRING, 5)),
        ((ItemID.GEM_SWORD, 1), (ItemID.WOOD, 5), (ItemID.GEM, 50)),
        ((ItemID.GEM_PICK, 1), (ItemID.WOOD, 5), (ItemID.GEM, 50)),
        ((ItemID.GEM_AXE, 1), (ItemID.WOOD, 5), (ItemID.GEM, 50)),
        ((ItemID.GEM_SHOVEL, 1), (ItemID.WOOD, 5), (ItemID.GEM, 50)),
        ((ItemID.GEM_HOE, 1), (ItemID.WOOD, 5), (ItemID.GEM, 50)),
        ((ItemID.GEM_FISH_SPEAR, 1), (ItemID.GEM, 50), (ItemID.STRING, 5)),
        ((ItemID.OBSIDIAN_FLOOR, 1), (ItemID.OBSIDIAN, 4)),
        ((ItemID.OBSIDIAN_WALL, 1), (ItemID.OBSIDIAN, 8)),
        ((ItemID.OBSIDIAN_DOOR, 1), (ItemID.OBSIDIAN, 8)),
        ((ItemID.SCRINIUM, 1), (ItemID.OBSIDIAN, 20), (ItemID.LAPIS, 20), (ItemID.BOOK, 10), (ItemID.GOLD_BAR, 5),
         (ItemID.IRON_BAR, 5), (ItemID.BONE, 10)),
    ),
    MobID.LOOM: (
        ((ItemID.STRING, 4), (ItemID.CLOTH, 1),),
        ((ItemID.CLOTH, 1), (ItemID.STRING, 4)),
        ((ItemID.BED, 1), (ItemID.WOOD, 10), (ItemID.CLOTH, 10)),
        ((ItemID.BOOK, 1), (ItemID.CLOTH, 20), (ItemID.STRING, 10), (ItemID.SLIME, 10)),
    ),
    MobID.CAULDRON: (
        ((ItemID.COCKTAIL, 1), (ItemID.BOTTLE, 1), (ItemID.APPLE, 1), (ItemID.COCONUT, 1), (ItemID.POKE_PEAR, 1)),
        ((ItemID.SWIM_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.FISH, 5), (ItemID.SLIME, 5), (ItemID.LAPIS, 1)),
        ((ItemID.LAVA_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.FIRE_FISH, 5), (ItemID.ASH, 10), (ItemID.LAPIS, 1)),
        ((ItemID.SWIM_LAVA_POTION, 1), (ItemID.SWIM_POTION, 1), (ItemID.LAVA_POTION, 1), ),
        ((ItemID.LAVA_WALK_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.OBSIDIAN, 10), (ItemID.ASH, 10), (ItemID.LAPIS, 1)),
        ((ItemID.HEALTH_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.BONE, 20), (ItemID.COOKED_TUBER, 5), (ItemID.LAPIS, 1)),
        ((ItemID.STAMINA_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.POKE_PEAR, 10), (ItemID.COCONUT, 10),
         (ItemID.GOLD_BAR, 1), (ItemID.LAPIS, 1)),
        ((ItemID.INVISIBLE_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.GLASS, 10), (ItemID.FUNGUS, 10), (ItemID.LAPIS, 1)),
        ((ItemID.IRONSKIN_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.IRON_BAR, 5), (ItemID.BONE, 10), (ItemID.LAPIS, 1)),
        ((ItemID.GOLDSKIN_POTION, 1), (ItemID.IRONSKIN_POTION, 1), (ItemID.GOLD_BAR, 5), (ItemID.LAPIS, 1)),
        ((ItemID.GEMSKIN_POTION, 1), (ItemID.GOLDSKIN_POTION, 1), (ItemID.GEM, 15), (ItemID.LAPIS, 1)),
        ((ItemID.HOVER_POTION, 1), (ItemID.BOTTLE, 1), (ItemID.FAIRY_DUST, 10), (ItemID.CLOUD, 10), (ItemID.LAPIS, 1)),
        ((ItemID.FERTILIZER, 1), (ItemID.DIRT, 2), (ItemID.BONE, 5), (ItemID.TUBER, 5)),
        ((ItemID.BOMB, 1), (ItemID.SAND, 15), (ItemID.COAL, 15), (ItemID.STRING, 10)),
        ((ItemID.RED_BOMB, 1), (ItemID.SAND, 25), (ItemID.ASH, 25), (ItemID.COAL, 25), (ItemID.STRING, 20),),
        ((ItemID.WHITE_BOMB, 1), (ItemID.SAND, 50), (ItemID.ASH, 50), (ItemID.COAL, 50), (ItemID.STRING, 30),
         (ItemID.QUARTZ, 10)),
    ),
    MobID.SCRINIUM: (
        ((ItemID.SKY_TORCH, 2), (ItemID.WOOD, 2), (ItemID.CLOUD, 1)),
        ((ItemID.CLOUD_FLOOR, 1), (ItemID.CLOUD, 4)),
        ((ItemID.CLOUD_BRICKS, 1), (ItemID.CLOUD, 8)),
        ((ItemID.CLOUD_DOOR, 1), (ItemID.CLOUD, 8)),
        ((ItemID.GOLD_APPLE, 1), (ItemID.BOOK, 1), (ItemID.APPLE, 1), (ItemID.GOLD_BAR, 10), (ItemID.LAPIS, 5)),
        ((ItemID.WEB_STAFF, 1), (ItemID.BOOK, 1), (ItemID.STRING, 15), (ItemID.SPIDER_EYE, 8), (ItemID.BONE, 10),
         (ItemID.LAPIS, 5),),
        ((ItemID.MAGIC_EYE, 1), (ItemID.BOOK, 1), (ItemID.SPIDER_EYE, 8), (ItemID.QUARTZ, 1), ),
        ((ItemID.SPACESHIP, 1), (ItemID.CIRCUIT, 50), (ItemID.QUARTZ, 30), (ItemID.GEM, 30), (ItemID.GLASS, 20),
         (ItemID.IRON_BAR, 20), (ItemID.LAPIS, 10), (ItemID.FAIRY_DUST, 15),),
    ),
}

mob_damage = {
    MobID.GREEN_ZOMBIE: 1,
    MobID.GREEN_SLIME: 1,
    MobID.GREEN_SKELETON: 1,
    MobID.RED_ZOMBIE: 2,
    MobID.RED_SLIME: 2,
    MobID.RED_SKELETON: 2,
    MobID.WHITE_ZOMBIE: 3,
    MobID.WHITE_SLIME: 3,
    MobID.WHITE_SKELETON: 3,
    MobID.BLACK_ZOMBIE: 4,
    MobID.BLACK_SLIME: 4,
    MobID.BLACK_SKELETON: 4,
    MobID.AIR_WIZARD: 5,
    MobID.BAT: 0,
    MobID.FLAME_SKULL: 2,
    MobID.SPIDER: 2,
    MobID.HELL_SPIDER: 3,
    MobID.CLOUD_SPIDER: 4,
    MobID.FAIRY: 3,
    MobID.SPRITE: 1,
    MobID.UFO: 4,
}

mob_ai_timer = defaultdict(lambda: 2)
mob_ai_timer.update({
    MobID.GREEN_ZOMBIE: 3,
    MobID.GREEN_SLIME: 3,
    MobID.GREEN_SKELETON: 2,
    MobID.RED_ZOMBIE: 3,
    MobID.RED_SLIME: 3,
    MobID.RED_SKELETON: 2,
    MobID.WHITE_ZOMBIE: 3,
    MobID.WHITE_SLIME: 3,
    MobID.WHITE_SKELETON: 2,
    MobID.BLACK_ZOMBIE: 3,
    MobID.BLACK_SLIME: 2,
    MobID.BLACK_SKELETON: 2,
    MobID.AIR_WIZARD: 2,
    MobID.BAT: 1,
    MobID.FLAME_SKULL: 1,
    MobID.SPIDER: 1,
    MobID.HELL_SPIDER: 1,
    MobID.CLOUD_SPIDER: 1,
    MobID.SHADE: 1,
    MobID.FAIRY: 1,
    MobID.SPRITE: 2,
    MobID.UFO: 1,
})

mob_explosion = {  # first number is fuse + 1, second is radius of explosion
    MobID.BOMB: (11, 5),
    MobID.RED_BOMB: (21, 10),
    MobID.WHITE_BOMB: (31, 15),
    MobID.DEVIL: (6, 2),
}

mob_explode_dmg = {
    MobID.BOMB: 8,
    MobID.RED_BOMB: 10,
    MobID.WHITE_BOMB: 15,
    MobID.DEVIL: 5,
}


MobData = namedtuple("MobData", ("name", "graphic", "max_health", "tags",
                                 "recipies", "light"), defaults=(10, tuple(), None, 0))
mob_data = {
    MobID.PLAYER: MobData("player", (Graphic.PLAYER, Color.WHITE), 10, (MobTag.NO_DESPAWN,), tuple(), 0),
    MobID.BAT: MobData("bat", (Graphic.BAT, Color.BROWN), 5, (MobTag.AI_WANDER,)),
    MobID.DUCK: MobData("duck", (Graphic.DUCK, Color.YELLOW), 2, (MobTag.AI_FOLLOW, MobTag.SWAPPABLE)),
    MobID.DOG: MobData("dog", (Graphic.DOG, Color.BROWN), 2, (MobTag.AI_FOLLOW, MobTag.SWAPPABLE)),
    MobID.CAT: MobData("cat", (Graphic.CAT, Color.ORANGE), 2, (MobTag.AI_FOLLOW, MobTag.SWAPPABLE)),
    MobID.PIG: MobData("pig", (Graphic.PIG, Color.PINK), 2, (MobTag.AI_FOLLOW, MobTag.SWAPPABLE)),
    MobID.CHICKEN: MobData("chicken", (Graphic.CHICKEN, Color.WHITE), 2, (MobTag.AI_FOLLOW, MobTag.SWAPPABLE)),
    MobID.SHADE: MobData("shade", (Graphic.SHADE, Color.BLUE), 20, (MobTag.AI_FLEE, MobTag.NO_DESPAWN), tuple(), 1),
    MobID.FLAME_SKULL: MobData("fireskull", (Graphic.SKULL, Color.YELLOW), 20, (MobTag.AI_WANDER, MobTag.DAMAGE,),
                               tuple(), 1),
    MobID.FAIRY: MobData("pixie", (Graphic.FAIRY, Color.PINK), 5, (MobTag.AI_WANDER, MobTag.DAMAGE, MobTag.NO_DESPAWN),
                               tuple(), 1),
    MobID.SPRITE: MobData("sprite", (Graphic.FAIRY, Color.RED), 5, (MobTag.AI_FOLLOW, MobTag.DAMAGE, MobTag.NO_DESPAWN,
                                                                    MobTag.ALWAYS_SIM),
                         tuple(), 1),
    MobID.UFO: MobData("ufo", (Graphic.UFO, Color.GREEN), 5, (MobTag.AI_WANDER, MobTag.DAMAGE, MobTag.NO_DESPAWN,),
                          tuple(), 1),
    MobID.SPIDER: MobData("spider", (Graphic.SPIDER, Color.MED_GRAY), 10, (MobTag.AI_SPIDER, MobTag.DAMAGE,)),
    MobID.HELL_SPIDER: MobData("hellspider", (Graphic.SPIDER, Color.RED), 10, (MobTag.AI_SPIDER, MobTag.DAMAGE)),
    MobID.CLOUD_SPIDER: MobData("skyspider", (Graphic.SPIDER, Color.LIGHT_BLUE), 10, (MobTag.AI_SPIDER, MobTag.DAMAGE,
                                                                                      MobTag.NO_DESPAWN)),
    MobID.GREEN_ZOMBIE: MobData("zombie", (Graphic.ZOMBIE, Color.MOB_GREEN), 10, (MobTag.AI_FOLLOW, MobTag.DAMAGE)),
    MobID.GREEN_SLIME: MobData("slime", (Graphic.SLIME, Color.MOB_GREEN), 5, (MobTag.AI_JUMP, MobTag.DAMAGE)),
    MobID.GREEN_SKELETON: MobData("skeleton", (Graphic.SKELETON, Color.MOB_GREEN), 10,
                                  (MobTag.PUSHABLE, MobTag.AI_SHOOT, MobTag.DAMAGE)),
    MobID.RED_ZOMBIE: MobData("zombie", (Graphic.ZOMBIE, Color.MOB_RED), 10, (MobTag.AI_FOLLOW, MobTag.DAMAGE)),
    MobID.RED_SLIME: MobData("slime", (Graphic.SLIME, Color.MOB_RED), 5, (MobTag.AI_JUMP, MobTag.DAMAGE)),
    MobID.RED_SKELETON: MobData("skeleton", (Graphic.SKELETON, Color.MOB_RED), 10,
                                  (MobTag.PUSHABLE, MobTag.AI_SHOOT, MobTag.DAMAGE)),
    MobID.WHITE_ZOMBIE: MobData("zombie", (Graphic.ZOMBIE, Color.MOB_WHITE), 10, (MobTag.AI_FOLLOW, MobTag.DAMAGE)),
    MobID.WHITE_SLIME: MobData("slime", (Graphic.SLIME, Color.MOB_WHITE), 5, (MobTag.AI_JUMP, MobTag.DAMAGE)),
    MobID.WHITE_SKELETON: MobData("skeleton", (Graphic.SKELETON, Color.MOB_WHITE), 10,
                                  (MobTag.PUSHABLE, MobTag.AI_SHOOT, MobTag.DAMAGE)),
    MobID.BLACK_ZOMBIE: MobData("zombie", (Graphic.ZOMBIE, Color.MOB_BLACK), 10, (MobTag.AI_FOLLOW, MobTag.DAMAGE,
                                                                                  MobTag.NO_DESPAWN)),
    MobID.BLACK_SLIME: MobData("slime", (Graphic.SLIME, Color.MOB_BLACK), 5, (MobTag.AI_JUMP, MobTag.DAMAGE,
                                                                              MobTag.NO_DESPAWN)),
    MobID.BLACK_SKELETON: MobData("skeleton", (Graphic.SKELETON, Color.MOB_BLACK), 10,
                                  (MobTag.PUSHABLE, MobTag.AI_SHOOT, MobTag.DAMAGE, MobTag.NO_DESPAWN)),
    MobID.AIR_WIZARD: MobData("air wizard", (Graphic.AIR_WIZARD, Color.RED), 100, (MobTag.DAMAGE, MobTag.NO_DESPAWN,
                                                                                   MobTag.AI_AIR_WIZARD,
                                                                                   MobTag.ALWAYS_SIM)),
    MobID.WORKBENCH: MobData("workbench", (Graphic.WORKBENCH, Color.BROWN), 10,
                             (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                             recipies[MobID.WORKBENCH]),
    MobID.LOOM: MobData("loom", (Graphic.LOOM, Color.LIGHT_BROWN), 10,
                             (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                        recipies[MobID.LOOM]),
    MobID.OVEN: MobData("oven", (Graphic.OVEN, Color.LIGHT_BROWN), 10,
                             (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                        recipies[MobID.OVEN]),
    MobID.FURNACE: MobData("furnace", (Graphic.FURNACE, Color.MED_GRAY), 10,
                             (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                           recipies[MobID.FURNACE]),
    MobID.ANVIL: MobData("anvil", (Graphic.ANVIL, Color.LIGHT_GRAY), 10,
                             (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                         recipies[MobID.ANVIL]),
    MobID.CAULDRON: MobData("cauldron", (Graphic.CAULDRON, Color.MED_GRAY), 10,
                         (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                            recipies[MobID.CAULDRON]),
    MobID.SCRINIUM: MobData("scrinium", (Graphic.SKULL_BOOKS, Color.OBSIDIAN), 10,
                            (MobTag.PUSHABLE, MobTag.CRAFTING, MobTag.NO_DESPAWN, MobTag.FURNITURE),
                            recipies[MobID.SCRINIUM], 2),
    MobID.BOOKCASE: MobData("bookcase", (Graphic.BOOKCASE, Color.BROWN), 10,
                            (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 2),
    MobID.WOOD_LANTERN: MobData("wood lantern", (Graphic.LANTERN, Color.BROWN), 10,
                             (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 6),
    MobID.TORCH: MobData("torch", (Graphic.TORCH, Color.YELLOW), 8,
                             (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 3),
    MobID.SKY_TORCH: MobData("skytorch", (Graphic.TORCH2, Color.LIGHT_BLUE), 8,
                         (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 6),
    MobID.GOLD_TORCH: MobData("candelabra", (Graphic.TORCH3, Color.YELLOW), 8,
                         (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 10),
    MobID.IRON_LANTERN: MobData("iron lantern", (Graphic.LANTERN, Color.IRON), 10,
                                (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 10),
    MobID.GOLD_LANTERN: MobData("gold lantern", (Graphic.LANTERN, Color.GOLD), 10,
                                (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 14),
    MobID.GEM_LANTERN: MobData("gem lantern", (Graphic.LANTERN, Color.GEM), 10,
                                (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.FURNITURE), tuple(), 18),
    MobID.BED: MobData("bed", (Graphic.BED, Color.RED), 10,
                               (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.BED, MobTag.FURNITURE), tuple(),),
    MobID.BOMB: MobData("bomb", (Graphic.BOMB, Color.MED_GRAY), 10,
                       (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.EXPLODE, MobTag.FURNITURE), tuple(), ),
    MobID.RED_BOMB: MobData("megabomb", (Graphic.BOMB, Color.RED), 10,
                       (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.EXPLODE, MobTag.FURNITURE), tuple(), ),
    MobID.WHITE_BOMB: MobData("nuke", (Graphic.BOMB, Color.WHITE), 10,
                            (MobTag.PUSHABLE, MobTag.NO_DESPAWN, MobTag.EXPLODE, MobTag.ALWAYS_SIM,
                             MobTag.FURNITURE), tuple(), ),
    MobID.DEVIL: MobData("bomb devil", (Graphic.DEVIL, Color.RED), 20, (MobTag.AI_FOLLOW, MobTag.DAMAGE,
                                                                        MobTag.EXPLODE,)),
}


class Mob:
    def __init__(self, mobid: MobID):
        self.id = mobid
        self.mob_data = mob_data[self.id]
        self.name = self.mob_data.name
        self.graphic = self.mob_data.graphic
        self.max_health = self.mob_data.max_health
        self.health = self.max_health
        self.tags = self.mob_data.tags
        self.recipies = self.mob_data.recipies
        self.light = self.mob_data.light
        self.target_space = None
        self.last_pos = (0, 0)
        self.last_dir = Point(0, -1)  # assume the last direction was up
        self.state = 'wander'
        self.ai_tick = 0
        self.ai_timer = mob_ai_timer[self.id]
        self.ai_state_timer = self.ai_tick
        self.ai_state_freq = 50
        self.fuse = 0

    def has_tag(self, tag: MobTag) -> bool:
        return tag in self.tags
